export { default as H1 } from "./H1.astro"
export { default as H2 } from "./H2.astro"
export { default as H3 } from "./H3.astro"
export { default as LI } from "./LI.astro"
export { default as Text } from "./Text.astro"
