export { Cancel } from './Cancel'
export { Logo } from './Logo'
export { Mail } from './Mail'
export { Menu } from './Menu'
export { OpenNewWindow } from './OpenNewWindow'
export { Phone } from './Phone'
